"""Registers the NDK cc toolchains only when there is an NDK.

`register_toolchains` cannot be conditional, and toolchain resolution loads
every registered toolchain repo looking for a match. `rules_android_ndk`'s
repository rule fails during that fetch when `ANDROID_NDK_HOME` is unset, which
made an NDK a prerequisite of any target resolving any toolchain -- a formatter
among them.

`@androidsdk` already behaves the other way: it stubs when its variable is unset
and fails later, at the target that needs it. This gives the NDK that shape.
With the variable set, nothing changes.

Without an NDK, what fails is a CMake plugin (in plugins.bzl, which resolves the
NDK on first use and explains itself) and anything needing the Android cc
toolchain. Everything else builds, which is the point.
"""

load("@rules_android_ndk//:rules.bzl", "android_ndk_repository")

_STUB_BUILD = """# Generated by //tools/flutter:ndk.bzl -- do not edit.
#
# ANDROID_NDK_HOME was unset, so this declares no toolchains: registering none
# lets resolution carry on instead of failing the fetch workspace-wide. Set the
# variable and rebuild to get the real repository.
package(default_visibility = ["//visibility:public"])
"""

def _stub_ndk_repository_impl(ctx):
    ctx.file("BUILD.bazel", _STUB_BUILD)

_stub_ndk_repository = repository_rule(
    implementation = _stub_ndk_repository_impl,
    doc = "An @androidndk that exists but declares no toolchains.",
)

def _android_ndk_impl(module_ctx):
    if module_ctx.getenv("ANDROID_NDK_HOME"):
        android_ndk_repository(name = "androidndk")
    else:
        _stub_ndk_repository(name = "androidndk")

android_ndk = module_extension(
    implementation = _android_ndk_impl,
    doc = "Creates @androidndk, or a toolchain-less stub when there is no NDK.",
    environ = ["ANDROID_NDK_HOME"],
)
