"""Provides stable upstream NDK and CMake repositories.

The NDK repository is always created from `rules_android_ndk` and declares the
same repositories on every invocation. The CMake marker repository validates the
NDK and remains environment-sensitive -- it reads `ANDROID_NDK_HOME` when
fetched and fails with an actionable diagnostic if no NDK is present.
"""

load("@rules_android_ndk//:rules.bzl", "android_ndk_repository")

_MIN_NDK_MAJOR = 28

_CMAKE_STUB_BUILD = """# Generated by //tools/flutter:ndk.bzl -- do not edit.
package(default_visibility = ["//visibility:public"])

genrule(
    name = "ndk_source_properties_missing",
    outs = ["ndk_source_properties_missing.txt"],
    cmd = "echo 'Dart-half native plugins require ANDROID_NDK_HOME set to an NDK 28.0.0 or newer when an Android Consumer Module registers NDK toolchains. No NDK is configured; the repository fetch intentionally fails here with this diagnostic.' >&2; exit 1",
)

filegroup(
    name = "ndk_source_properties",
    srcs = [":ndk_source_properties_missing"],
)
"""

def _androidndk_cmake_repository_impl(ctx):
    ndk = ctx.os.environ.get("ANDROID_NDK_HOME", "").strip()
    if not ndk:
        ctx.file("BUILD.bazel", _CMAKE_STUB_BUILD)
        return

    properties = ctx.path("{}/source.properties".format(ndk))
    if not properties.exists:
        fail("ANDROID_NDK_HOME={} does not look like an NDK: no source.properties".format(ndk))

    revision = None
    for line in ctx.read(properties).split("\n"):
        if line.startswith("Pkg.Revision"):
            revision = line.split("=")[1].strip()
            break
    if not revision:
        fail("Could not read Pkg.Revision from {}/source.properties".format(ndk))

    major = revision.split(".")[0]
    if not major.isdigit() or int(major) < _MIN_NDK_MAJOR:
        # Not a style preference. Below 28 emits 4 KB-aligned LOAD segments;
        # a 4 KB-aligned .so segfaults the loader on a 16 KB-page device (API 35)
        # with no dlerror() or log line; refusing here is the only loud moment.
        fail(
            "ANDROID_NDK_HOME points at NDK {}, but {}.0.0 or newer is required.\n".format(
                revision,
                _MIN_NDK_MAJOR,
            ) +
            "NDK 27 and older default to 4 KB page alignment; such a .so " +
            "crashes the dynamic loader on 16 KB-page devices (Android 15, " +
            "API 35) rather than failing to load cleanly.",
        )

    toolchain_file = ctx.path("{}/build/cmake/android.toolchain.cmake".format(ndk))
    if not toolchain_file.exists:
        fail("NDK at {} has no build/cmake/android.toolchain.cmake".format(ndk))

    ctx.symlink(properties, "source.properties")
    ctx.file(
        "BUILD.bazel",
        """package(default_visibility = ["//visibility:public"])

filegroup(
    name = "ndk_source_properties",
    srcs = ["source.properties"],
)
""",
    )

_androidndk_cmake_repository = repository_rule(
    implementation = _androidndk_cmake_repository_impl,
    doc = "Exposes NDK source.properties when an NDK is available.",
    local = True,
    environ = ["ANDROID_NDK_HOME"],
)

def _android_ndk_impl(_module_ctx):
    android_ndk_repository(name = "androidndk")
    _androidndk_cmake_repository(name = "androidndk_cmake")

android_ndk = module_extension(
    implementation = _android_ndk_impl,
    doc = "Creates @androidndk and @androidndk_cmake repositories without reading the NDK path.",
)
