"""Bazel targets for the Android half of Flutter plugins.

A Flutter plugin is a pub package that also ships a complete AGP library module
under `<package>/android/` -- its own manifest, sources, resources and Maven
dependencies. Gradle picks these up in `FlutterAppPluginLoaderPlugin`, which
reads `.flutter-plugins-dependencies` and `include`s each plugin's `android/`
directory as a subproject, then attaches it to the app as a `<buildType>Api`
dependency.

This does the same from the same input file: read the metadata, stage each
plugin's package root into an external repository, and generate one target per
plugin. A plugin whose `build.gradle` drives CMake also gets its `CMakeLists`
built with the NDK, and the resulting `.so` attached to the same label.

Two properties are deliberate, because they are what makes the gate in
`_GATED_REASONS` reversible rather than permanent:

  1. **The strategy is not in the label.** `@flutter_plugins//<name>` is the
     label whether the plugin was built from source alone or from source plus
     CMake. Moving a plugin between them is a change to this file, never to a
     consumer.

  2. **Plugins are classified by *reason*, not by decision.** A plugin carries
     reason codes like `ndk_build`; routing is a single lookup against
     `_GATED_REASONS`. When a reason becomes supported, deleting its entry from
     that list re-routes every plugin carrying it at once -- which is exactly
     how `external_native_build` stopped being gated.
"""

load(":embedding.bzl", "FLUTTER_EMBEDDING_ARTIFACTS")
load(":maven.bzl", "highest_versions", "maven_label")

# Reason codes a plugin can carry. A plugin with none is built from source.
#
#   external_native_build  build.gradle drives CMake/ndk-build. CMake is now
#                          built (see _NATIVE_TEMPLATE); ndk-build is not, and
#                          is reported as `ndk_build` instead.
#   ndk_build              build.gradle drives ndk-build (Android.mk), which
#                          nothing here runs.
#   unresolved_dep         a dependency coordinate could not be read statically:
#                          a variable defined outside the file, or a version
#                          supplied by a BOM. Resolving it would mean executing
#                          Groovy.
#
# Removing an entry here is the whole mechanism for widening support: no
# consumer, and no other part of this file, encodes the distinction.
# `external_native_build` left this list when the CMake path landed.
_GATED_REASONS = [
    "ndk_build",
    "unresolved_dep",
]

_NATIVE_BUILD_MARKERS = [
    "externalNativeBuild",
    "CMakeLists",
    "ndkVersion",
]

# ndk-build is the other externalNativeBuild backend. It is driven by an
# Android.mk rather than a CMakeLists, so the CMake path cannot build it.
_NDK_BUILD_MARKERS = [
    "ndkBuild",
    "Android.mk",
]

# NDK 28 is the floor because it is the first release that defaults to 16 KB
# page alignment. NDK 27 *supports* 16 KB but still emits 4 KB-aligned LOAD
# segments by default, and a 4 KB-aligned .so does not merely fail to load on
# an API 35 device -- it segfaults the loader, with no dlerror() and no message.
# Measured across 26.3 / 27.2 / 28.2; see docs/plugins.md.
_MIN_NDK_MAJOR = 28

# Dependency configurations that put classes on the compile/runtime classpath.
# `testImplementation` and `androidTestImplementation` are deliberately absent:
# they carry a capital I, so they do not match, and they are not part of the
# published library anyway.
_DEP_CONFIGURATIONS = [
    "implementation",
    "api ",
    "api(",
    "compileOnly",
    "runtimeOnly",
]

_BUILD_LOADS = """# Generated by //tools/flutter:plugins.bzl -- do not edit.
load("@rules_android//rules:rules.bzl", "android_library")
"""

# Kotlin is the default language of the Flutter plugin template, so a plugin's
# Android half is as likely to be .kt as .java -- rive_common's is. android_library
# rejects .kt outright ("misplaced here, expected .java or .srcjar"), so those
# plugins are built with kt_android_library, which rules_kotlin derives from
# android_library's own attributes and is otherwise a drop-in.
_KOTLIN_BUILD_LOADS = """load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")
"""

# Loaded only into the BUILD of a plugin that actually has a CMake build, so a
# project with no native plugins never pulls rules_foreign_cc into analysis.
_NATIVE_BUILD_LOADS = """load("@rules_foreign_cc//foreign_cc:defs.bzl", "cmake")
load("@rules_java//java:defs.bzl", "java_import")
load("{defs}", "android_native_lib_jar")
"""

_BUILD_PACKAGE = """
package(default_visibility = ["//visibility:public"])
"""

# Kept for the aggregate and gated BUILD files, which need no extra loads.
_BUILD_HEADER = _BUILD_LOADS + _BUILD_PACKAGE

_PLUGIN_TEMPLATE = """
# {name}, built from the Gradle module the pub package ships.
# {path}
{rule}(
    name = "{name}",
    srcs = {srcs},
    manifest = "android/src/main/AndroidManifest.xml",
    # The plugin manifest carries more than a package name -- connectivity_plus
    # declares ACCESS_NETWORK_STATE -- and it has to reach the APK, so it is
    # exported up the dependency chain to android_binary rather than consumed
    # locally.
    #
    # 1 rather than True for kt_android_library: it is built from rules_android's
    # raw attrs, where exports_manifest is the underlying tri-state int, while the
    # android_library *macro* accepts a bool and converts.
    exports_manifest = {exports_manifest},
    custom_package = "{package}",
    resource_files = {resource_files},
    deps = [
        # The embedding is an `api` dependency of every plugin under Gradle, so
        # AGP can desugar the default interface methods FlutterPlugin declares.
        # See flutter/flutter#72185 and PluginHandler.addEmbeddingDependencyToPlugin.
        "{embedding}",{deps}
    ],
)
"""

# The native half. Three targets rather than one because each boundary is a
# different concern: cmake() compiles, android_native_lib_jar packages (and
# pins the Android platform), java_import puts the jar on the classpath where
# android_binary looks for lib/<abi>/*.so.
#
# The .so is attached to the plugin's android_library as an ordinary dep, so it
# reaches the APK through @flutter_plugins//:all like everything else -- the
# label a consumer names is still just @flutter_plugins//<name>.
_NATIVE_TEMPLATE = """
# {name}'s native half: {libs}, from the plugin's own CMakeLists.
#
# The plugin's CMakeLists is run as written, against the NDK's own
# android.toolchain.cmake -- the toolchain file AGP passes and the one the
# CMakeLists was tested against. Handing it over as a CMAKE_TOOLCHAIN_FILE
# cache entry suppresses rules_foreign_cc's synthesized crosstool, which does
# not link the NDK C++ STL.
#
# lib_source is the whole package root, enumerated. A plugin's CMakeLists
# routinely reaches outside android/ -- rive_common's pulls in ../ios and,
# through that, ../common_source -- and which directories it reaches into
# cannot be known without evaluating it, so no narrower set is predictable
# from here.
filegroup(
    name = "{name}_native_srcs",
    srcs = {native_srcs},
)

cmake(
    name = "{name}_native",
    lib_source = ":{name}_native_srcs",
    # CMakeLists.txt lives under android/, but its sources do not. Note
    # rules_foreign_cc's detect_root() picks the topmost *file* dirname, so this
    # is relative to the package root only because the package root has files.
    working_directory = "{cmake_dir}",
    cache_entries = {{
        "CMAKE_TOOLCHAIN_FILE": "{toolchain_file}",
        "ANDROID_ABI": "{abi}",
        "ANDROID_PLATFORM": "android-{api_level}",
        # NDK 28 defaults to 16 KB page alignment, but that default does not
        # survive this path: rules_android_ndk's cc_toolchain passes an explicit
        # -Wl,-z,max-page-size=4096, and rules_foreign_cc forwards the toolchain's
        # link flags into CMAKE_SHARED_LINKER_FLAGS. So the NDK version alone is
        # not enough here and the alignment has to be restated.
        #
        # cache_entries are appended *after* the toolchain's own values, so this
        # is the later -z max-page-size and wins.
        #
        # Getting this wrong is not a clean failure: a 4 KB-aligned .so
        # segfaults the loader on a 16 KB-page device (API 35), with no
        # dlerror() and nothing in logcat. Verify with
        # `llvm-readelf -l <so> | grep LOAD` -- want 0x4000, not 0x1000.
        "CMAKE_SHARED_LINKER_FLAGS": "-Wl,-z,max-page-size=16384",
    }},
    generate_args = ["-GNinja"],
    # The plugin declares no install() rules -- there is nothing for
    # `cmake --install` to do -- so the libraries are lifted out by hand.
    install = False,
    out_shared_libs = {libs},
    postfix_script = "mkdir -p $$INSTALLDIR/lib && cp {lib_copy} $$INSTALLDIR/lib/",
)

android_native_lib_jar(
    name = "{name}_native_jar",
    src = [":{name}_native"],
    abi = "{abi}",
)

java_import(
    name = "{name}_native_import",
    jars = [":{name}_native_jar"],
)
"""

_GATED_TEMPLATE = """
# {name} is not supported: {reasons}.
#
# This target exists so the rest of the repository still fetches and builds.
# Building it fails with the reason; nothing else is affected.
genrule(
    name = "{name}_unsupported",
    outs = ["{name}_unsupported.java"],
    cmd = "echo 'Flutter plugin {name} is not supported: {reasons}.' >&2; " +
          "echo 'To fix, {hint}, or drop a reason code from ' >&2; " +
          "echo '_GATED_REASONS in tools/flutter/plugins.bzl.' >&2; " +
          "exit 1",
)

android_library(
    name = "{name}",
    srcs = [":{name}_unsupported"],
)
"""

_MODULE_SEGMENT_HEADER = """# Generated by //tools/flutter:plugins.bzl -- do not edit by hand.
#
# The complete Maven artifact list: the Flutter embedding's own dependencies
# (from //tools/flutter:embedding.bzl) merged with the coordinates extracted
# from every plugin's android/build.gradle. Regenerate with:
#
#     bazel build //app:plugins_check
#
# which prints this file's expected contents when it drifts.
#
# This is the *only* maven.install for @flutter_maven, deliberately. Two install
# tags sharing a repository name merge into one resolution and the later tag
# wins outright -- not highest-version, not declaration order -- so splitting
# the list let a plugin silently downgrade an artifact the embedding declared.
# One list, resolved once, with highest-wins applied across all of it.
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "flutter_maven",
    artifacts = [{artifacts}
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    # Every artifact above is already reduced to one version, so "pinned" makes
    # those chosen versions authoritative over transitive suggestions rather
    # than failing resolution when a pom asks for something older.
    version_conflict_policy = "pinned",
)
use_repo(maven, "flutter_maven")
"""




def _module_segment(coordinates):
    return _MODULE_SEGMENT_HEADER.format(
        artifacts = "".join([
            "\n        \"{}\",".format(c)
            for c in highest_versions(coordinates)
        ]),
    )


def _strip_buildscript(text):
    """Drop `buildscript { ... }` blocks.

    Their `classpath` entries are the AGP version the plugin builds *itself*
    with, not dependencies of the produced library, so counting them would gate
    every plugin in existence.
    """
    out = []
    rest = text
    for _ in range(10):
        start = rest.find("buildscript")
        if start == -1:
            break
        brace = rest.find("{", start)
        if brace == -1:
            break
        depth = 0
        end = -1
        for i in range(brace, len(rest)):
            c = rest[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        if end == -1:
            break
        out.append(rest[:start])
        rest = rest[end:]
    out.append(rest)
    return "".join(out)


def _quoted(line):
    """The first single- or double-quoted run in `line`, or None."""
    for quote in ["\"", "'"]:
        start = line.find(quote)
        if start == -1:
            continue
        end = line.find(quote, start + 1)
        if end == -1:
            continue
        return line[start + 1:end]
    return None


def _collect_variables(body):
    """Gradle variables assigned a string literal in this file.

    Covers `ext.foo = '1.2'`, `foo = '1.2'` inside an `ext {}` block, and
    `def foo = '1.2'`. This is string scraping, not evaluation -- anything
    computed, conditional, or defined in the root project stays unresolved and
    becomes an `unresolved_dep` reason rather than a guess.
    """
    variables = {}
    for line in body.split("\n"):
        stripped = line.strip()
        if stripped.startswith("//"):
            continue
        if "=" not in stripped:
            continue
        name = stripped.split("=")[0].strip()
        for prefix in ["def ", "ext."]:
            if name.startswith(prefix):
                name = name[len(prefix):].strip()
        if not name or " " in name or "." in name:
            continue
        value = _quoted(stripped[stripped.find("=") + 1:])
        if value != None and "$" not in value:
            variables[name] = value
    return variables


def _substitute(coordinate, variables):
    """Replace $var / ${var} in a coordinate. Returns None if any is unknown."""
    out = ""
    rest = coordinate
    for _ in range(10):
        at = rest.find("$")
        if at == -1:
            out += rest
            return out
        out += rest[:at]
        rest = rest[at + 1:]
        if rest.startswith("{"):
            end = rest.find("}")
            if end == -1:
                return None
            name = rest[1:end]
            rest = rest[end + 1:]
        else:
            end = len(rest)
            for i in range(len(rest)):
                c = rest[i]
                if not (c.isalnum() or c == "_"):
                    end = i
                    break
            name = rest[:end]
            rest = rest[end:]
        if name not in variables:
            return None
        out += variables[name]
    return None


def _extract_dependencies(build_gradle_text):
    """Return (coordinates, reasons) for one plugin's build.gradle.

    Gradle is the only thing that can truly evaluate this file, but the
    dependency block is overwhelmingly literal in practice, and the cases that
    are not fall into a small set that this reports rather than guesses at.
    """
    body = _strip_buildscript(build_gradle_text)
    variables = _collect_variables(body)

    coordinates = []
    reasons = []
    for marker in _NATIVE_BUILD_MARKERS:
        if marker in body:
            reasons.append("external_native_build")
            break

    # ndk-build is a separate backend from CMake and nothing here runs it, so it
    # is reported under its own code and stays gated.
    for marker in _NDK_BUILD_MARKERS:
        if marker in body:
            if "ndk_build" not in reasons:
                reasons.append("ndk_build")
            break

    for line in body.split("\n"):
        stripped = line.strip()
        if stripped.startswith("//"):
            continue

        matched = False
        for configuration in _DEP_CONFIGURATIONS:
            if stripped.startswith(configuration):
                matched = True
                break
        if not matched:
            continue

        # `implementation platform("...")` imports a BOM: the coordinates it
        # governs are then written without a version. rules_jvm_external can
        # express this via maven.install(boms = ...), but picking the BOM up
        # automatically would mean resolving its version too, so it is reported.
        if "platform(" in stripped:
            if "unresolved_dep" not in reasons:
                reasons.append("unresolved_dep")
            continue

        coordinate = _quoted(stripped)
        if coordinate == None:
            continue

        resolved = _substitute(coordinate, variables)

        # kotlin-stdlib comes from the rules_kotlin toolchain, so its version is
        # not ours to resolve and declaring it would fight the toolchain. This is
        # the single most common unresolved coordinate in the pub ecosystem --
        # the plugin template writes `$kotlin_version`, defined in the *root*
        # project, so it is never readable from the plugin's own build.gradle.
        if coordinate.startswith("org.jetbrains.kotlin:kotlin-stdlib"):
            continue

        if resolved == None or resolved.count(":") != 2:
            if "unresolved_dep" not in reasons:
                reasons.append("unresolved_dep")
            continue

        if resolved not in coordinates:
            coordinates.append(resolved)

    return coordinates, reasons




_DART_REGISTRANT_TEMPLATE = '''//
// Generated by //tools/flutter:plugins.bzl -- do not edit.
//
// The Dart half of plugin registration. GeneratedPluginRegistrant.java
// instantiates each plugin's *native* class; a federated plugin also ships a
// Dart implementation of its platform interface, declared as `dartPluginClass`
// in the plugin's pubspec, and that half is registered from here.
//
// Nothing imports this file. frontend_server is given it via --source, and the
// engine finds it through the `flutter.dart_plugin_registrant` environment
// define, which package:flutter/src/dart_plugin_registrant.dart reads into a
// const. Hence the vm:entry-point pragmas: nothing references these symbols, so
// tree shaking would otherwise drop them.

import 'dart:io'; // flutter_ignore: dart_io_import.

{imports}
@pragma('vm:entry-point')
class _PluginRegistrant {{

  @pragma('vm:entry-point')
  static void register() {{
    if (Platform.isAndroid) {{
{registrations}    }}
  }}
}}
'''

_DART_REGISTRATION = '''      try {{
        {name}.{dart_class}.registerWith();
      }} catch (err) {{
        print(
          '`{name}` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
      }}
'''


def _dart_plugin_class(ctx, package_root, name):
    """Read `flutter: plugin: platforms: android: dartPluginClass` from a pubspec.

    Returns (dartClass, dartFileName) or (None, None). The metadata file does
    not carry these -- only Gradle's view of a plugin is in there -- so the
    plugin's own pubspec is the source.

    This is indentation-driven rather than a real YAML parse, which is why it
    checks the nesting it walks rather than scanning for a bare key: a
    `dartPluginClass` under ios: must not be picked up for android.
    """
    pubspec = ctx.path("{}/pubspec.yaml".format(package_root))
    if not pubspec.exists:
        return None, None

    in_flutter = False
    in_plugin = False
    in_platforms = False
    in_android = False
    dart_class = None
    dart_file = None

    for raw in ctx.read(pubspec).split("\n"):
        line = raw.split("#")[0].rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        key = line.strip().split(":")[0].strip()
        value = line.strip()[len(key) + 1:].strip() if ":" in line else ""

        if indent == 0:
            in_flutter = key == "flutter"
            in_plugin = False
            in_platforms = False
            in_android = False
            continue
        if not in_flutter:
            continue
        if indent <= 2:
            in_plugin = key == "plugin"
            in_platforms = False
            in_android = False
            continue
        if not in_plugin:
            continue
        if indent <= 4:
            in_platforms = key == "platforms"
            in_android = False
            continue
        if not in_platforms:
            continue
        if indent <= 6:
            in_android = key == "android"
            continue
        if in_android:
            if key == "dartPluginClass":
                dart_class = value
            elif key == "dartFileName":
                dart_file = value

    if dart_class == None:
        return None, None
    # flutter_tools defaults the file to <pluginName>.dart when unspecified.
    return dart_class, dart_file if dart_file else "{}.dart".format(name)


def _manifest_package(ctx, manifest_path):
    """Read the `package=` attribute from a library manifest.

    AGP takes this from the `namespace` in build.gradle now, but the attribute
    is still present in every plugin manifest and is what Bazel's android rules
    read, so it is the more direct source.
    """
    text = ctx.read(manifest_path)
    marker = "package="
    at = text.find(marker)
    if at == -1:
        return None
    quote = text[at + len(marker)]
    end = text.find(quote, at + len(marker) + 1)
    return text[at + len(marker) + 1:end]


def _list_files(ctx, root, subdir, extensions):
    """Enumerate files under `root/subdir`, returned as `subdir`-relative paths.

    Files are listed here rather than left to a `glob()` in the generated BUILD
    because the tree is reached through a directory symlink into ~/.pub-cache.
    Enumerating makes the generated target explicit and reviewable, and pub
    package contents are immutable for a given version, so nothing is lost.
    """
    found = []
    directory = root.get_child(subdir)
    if not directory.exists:
        return found

    pending = [directory]
    for _ in range(1000):
        if not pending:
            break
        current = pending.pop()
        for child in current.readdir():
            if child.is_dir:
                pending.append(child)
                continue
            name = str(child)
            if extensions and not [e for e in extensions if name.endswith(e)]:
                continue
            found.append(name[len(str(root)) + 1:])
    return sorted(found)


def _list_all_files(ctx, root, skip_dirs):
    """Every file under `root`, as root-relative paths.

    Used for the CMake source set. Enumerated rather than globbed for the same
    reason the Java sources are: the tree is reached through symlinks into
    ~/.pub-cache. It also has to be the whole package root -- a plugin's
    CMakeLists routinely reaches outside android/, and which directories it
    reaches into cannot be known without evaluating it.
    """
    found = []
    pending = [root]

    # Bounded because a repository rule must terminate; a pub package is a few
    # hundred directories, so this is slack, not a limit anyone reaches.
    for _ in range(20000):
        if not pending:
            break
        current = pending.pop()
        for child in current.readdir():
            name = child.basename
            if name.startswith("."):
                continue
            if child.is_dir:
                if name not in skip_dirs:
                    pending.append(child)
                continue
            found.append(str(child)[len(str(root)) + 1:])
    return sorted(found)


def _cmake_subdirectory(build_gradle_text):
    """The directory holding the CMakeLists, relative to the package root.

    `externalNativeBuild { cmake { path "CMakeLists.txt" } }` names a path
    relative to the Gradle module, i.e. to android/.
    """
    at = build_gradle_text.find("externalNativeBuild")
    if at == -1:
        return "android"

    # `path` is the only string in the cmake block that matters; take the first
    # one after the marker rather than parsing Groovy.
    region = build_gradle_text[at:]
    path_at = region.find("path")
    if path_at == -1:
        return "android"
    relative = _quoted(region[path_at:region.find("\n", path_at) + 1 or len(region)])
    if not relative:
        return "android"

    # Keep the directory, drop the CMakeLists filename.
    parts = [p for p in relative.split("/") if p and p != "."]
    if parts and parts[-1].endswith(".txt"):
        parts = parts[:-1]
    return "/".join(["android"] + parts)


def _cmake_shared_libraries(cmakelists_text):
    """Names of the SHARED libraries a CMakeLists defines, as lib<name>.so.

    rules_foreign_cc has to be told what to expect, and getting this wrong is
    loud: the build fails with the file missing rather than producing a
    silently empty result.
    """
    libraries = []
    rest = cmakelists_text
    for _ in range(100):
        at = rest.find("add_library")
        if at == -1:
            break
        rest = rest[at + len("add_library"):]
        close = rest.find(")")
        if close == -1:
            break
        # Starlark's split() needs an explicit separator, so normalise the
        # whitespace CMake allows between arguments and drop the empties.
        head = rest[:close].replace("(", " ")
        for whitespace in ["\n", "\r", "\t"]:
            head = head.replace(whitespace, " ")
        arguments = [a for a in head.split(" ") if a]
        # add_library(<name> [STATIC|SHARED|MODULE] ...). Only SHARED produces a
        # .so; a STATIC helper library is linked into one and never shipped.
        if len(arguments) >= 2 and "SHARED" in arguments[1:]:
            name = arguments[0]
            if "$" not in name and "lib{}.so".format(name) not in libraries:
                libraries.append("lib{}.so".format(name))
    return libraries


def _ndk_root(ctx):
    """The NDK to build native plugins with, version-checked.

    Read from the same ANDROID_NDK_HOME that rules_android_ndk reads, so the
    cc_toolchain and the CMake toolchain file can never disagree about which
    NDK is in use.
    """
    ndk = ctx.getenv("ANDROID_NDK_HOME")
    if not ndk:
        fail(
            "This project has a Flutter plugin with a CMake native build, " +
            "which needs the Android NDK, but ANDROID_NDK_HOME is not set.\n" +
            "Set it to an NDK {}.0.0 or newer, e.g.\n".format(_MIN_NDK_MAJOR) +
            "    export ANDROID_NDK_HOME=$HOME/Library/Android/sdk/ndk/28.2.13676358",
        )

    properties = ctx.path("{}/source.properties".format(ndk))
    if not properties.exists:
        fail("ANDROID_NDK_HOME={} does not look like an NDK: no source.properties".format(ndk))

    revision = None
    for line in ctx.read(properties).split("\n"):
        if line.startswith("Pkg.Revision"):
            revision = line.split("=")[1].strip()
            break
    if not revision:
        fail("Could not read Pkg.Revision from {}/source.properties".format(ndk))

    major = revision.split(".")[0]
    if not major.isdigit() or int(major) < _MIN_NDK_MAJOR:
        # Not a style preference. Below 28 the NDK emits 4 KB-aligned LOAD
        # segments, and a 4 KB-aligned .so segfaults the loader on a 16 KB-page
        # device (API 35) with no dlerror() and no log line -- the APK builds,
        # installs and dies. Refusing here is the only loud moment available.
        fail(
            "ANDROID_NDK_HOME points at NDK {}, but {}.0.0 or newer is required.\n".format(
                revision,
                _MIN_NDK_MAJOR,
            ) +
            "NDK 27 and older default to 4 KB page alignment; such a .so " +
            "crashes the dynamic loader on 16 KB-page devices (Android 15, " +
            "API 35) rather than failing to load cleanly.",
        )

    toolchain_file = ctx.path("{}/build/cmake/android.toolchain.cmake".format(ndk))
    if not toolchain_file.exists:
        fail("NDK at {} has no build/cmake/android.toolchain.cmake".format(ndk))
    return str(toolchain_file)


def _flutter_plugins_impl(ctx):
    metadata = json.decode(ctx.read(ctx.attr.metadata))
    plugins = metadata.get("plugins", {}).get("android", [])
    overrides = {k: json.decode(v) for k, v in ctx.attr.overrides.items()}

    manifest = []
    all_coordinates = []
    dart_registrations = []

    # Resolved on first use, so a project with no CMake plugin needs no NDK at
    # all -- and one that does gets the version check before anything is
    # generated.
    toolchain_file = None
    for plugin in plugins:
        name = plugin["name"]
        package_root = plugin["path"].rstrip("/")

        # The Dart half is independent of whether there is anything to compile:
        # a Dart-only implementation of a federated plugin still has to register
        # its platform interface. Collected before the native_build check for
        # exactly that reason.
        dart_class, dart_file = _dart_plugin_class(ctx, package_root, name)
        if dart_class:
            dart_registrations.append((name, dart_class, dart_file))

        # Dart-only implementations have no Gradle module to build.
        if not plugin.get("native_build", True):
            continue

        # `path` is the package root; the Gradle module is one level down. It is
        # an absolute path into ~/.pub-cache, which is why plugins have to be
        # reached through an external repository at all: Bazel cannot glob
        # outside the workspace.
        android = "{}/android".format(package_root)

        build_gradle = ctx.path("{}/build.gradle".format(android))
        if not build_gradle.exists:
            build_gradle = ctx.path("{}/build.gradle.kts".format(android))
        if not build_gradle.exists:
            fail("Plugin {} declares an Android build but has no build.gradle at {}".format(name, android))

        coordinates, reasons = _extract_dependencies(ctx.read(build_gradle))
        # An override supplies coordinates the scraper could not read, which is
        # the per-plugin escape hatch from `unresolved_dep`. It is the only way
        # out for a BOM-versioned plugin: an AAR would not help, because an AAR
        # does not carry its dependencies.
        override = overrides.get(name)
        if override != None:
            coordinates = coordinates + [c for c in override if c not in coordinates]
            reasons = [r for r in reasons if r != "unresolved_dep"]

        gated = [r for r in reasons if r in _GATED_REASONS]

        if gated:
            # Deliberately not a fail(): that aborts the repository fetch, so a
            # single unsupported plugin makes every *other* plugin unfetchable
            # too. Emitting a target that fails when built keeps the label
            # present and correctly typed, so unrelated targets still build and
            # the error names the plugin that actually caused it.
            ctx.file(
                "{}/BUILD.bazel".format(name),
                _BUILD_HEADER + _GATED_TEMPLATE.format(
                    name = name,
                    reasons = ", ".join(gated),
                    hint = (
                        "supply its coordinates with plugins.override()"
                        if "unresolved_dep" in gated
                        else "port the module to CMake, which is built"
                    ),
                ),
            )
            manifest.append({
                "name": name,
                "reasons": reasons,
                "strategy": "gated",
                "coordinates": coordinates,
            })
            continue

        # Stage the package root as a real directory of symlinked entries,
        # rather than symlinking the package root itself.
        #
        # Symlinking the directory means ctx.file("<name>/BUILD.bazel") writes
        # *through* the symlink, landing a generated BUILD file inside
        # ~/.pub-cache -- mutating a cache that pub treats as immutable and
        # shares between every project on the machine.
        #
        # It also has to be the package root and not android/: a CMake plugin's
        # CMakeLists reaches outside the Gradle module (rive_common's reaches
        # into ../ios and, through that, ../common_source).
        for child in ctx.path(package_root).readdir():
            if child.basename.startswith("."):
                continue
            ctx.symlink(child, "{}/{}".format(name, child.basename))

        root = ctx.path(name)
        java_srcs = _list_files(ctx, root, "android/src/main/java", [".java"])
        kotlin_srcs = _list_files(ctx, root, "android/src/main/kotlin", [".kt"])

        # A plugin's java/ tree may hold .kt too -- the source set is what
        # build.gradle names, not what the directory is called -- so classify on
        # the extensions actually found rather than on the directory.
        kotlin_srcs = kotlin_srcs + _list_files(ctx, root, "android/src/main/java", [".kt"])
        srcs = java_srcs + kotlin_srcs
        if not srcs:
            fail("Plugin {} has no Android sources under {}/src/main".format(name, android))

        package = _manifest_package(ctx, root.get_child("android/src/main/AndroidManifest.xml"))
        if not package:
            fail("Plugin {} has no package= in its AndroidManifest.xml".format(name))

        # The native half, for plugins whose build.gradle drives CMake.
        native = ""
        native_deps = []
        if "external_native_build" in reasons:
            if toolchain_file == None:
                toolchain_file = _ndk_root(ctx)

            cmake_directory = _cmake_subdirectory(ctx.read(build_gradle))
            cmakelists = root.get_child(cmake_directory).get_child("CMakeLists.txt")
            if not cmakelists.exists:
                fail("Plugin {} declares externalNativeBuild but has no CMakeLists.txt at {}/{}".format(
                    name,
                    package_root,
                    cmake_directory,
                ))

            libraries = _cmake_shared_libraries(ctx.read(cmakelists))
            if not libraries:
                fail("Plugin {}'s CMakeLists at {}/{} defines no SHARED library".format(
                    name,
                    package_root,
                    cmake_directory,
                ))

            native = _NATIVE_TEMPLATE.format(
                name = name,
                libs = repr(libraries),
                lib_copy = " ".join(libraries),
                native_srcs = repr(_list_all_files(ctx, root, ["build"])),
                cmake_dir = cmake_directory,
                toolchain_file = toolchain_file,
                abi = ctx.attr.abi,
                api_level = ctx.attr.api_level,
            )
            native_deps = ["\n        \":{}_native_import\",".format(name)]

        ctx.file(
            "{}/BUILD.bazel".format(name),
            _BUILD_LOADS +
            (_KOTLIN_BUILD_LOADS if kotlin_srcs else "") +
            (_NATIVE_BUILD_LOADS.format(defs = ctx.attr.defs) if native else "") +
            _BUILD_PACKAGE +
            native +
            _PLUGIN_TEMPLATE.format(
                name = name,
                path = android,
                rule = "kt_android_library" if kotlin_srcs else "android_library",
                exports_manifest = "1" if kotlin_srcs else "True",
                srcs = repr(srcs),
                resource_files = repr(_list_files(ctx, root, "android/src/main/res", [])),
                package = package,
                deps = "".join(
                    # Plugins depend on each other: image_picker_android needs
                    # FlutterLifecycleAdapter from flutter_plugin_android_lifecycle.
                    # Gradle wires this in PluginHandler.configurePluginDependencies
                    # from the same "dependencies" field.
                    [
                        "\n        \"//{n}:{n}\",".format(n = d)
                        for d in plugin.get("dependencies", [])
                    ] + [
                        "\n        \"{}\",".format(maven_label(c))
                        for c in coordinates
                    ] + native_deps,
                ),
                embedding = ctx.attr.embedding,
            ),
        )
        manifest.append({
            "name": name,
            "reasons": reasons,
            "strategy": "source+cmake" if native else "source",
            "coordinates": coordinates,
        })
        all_coordinates.extend([c for c in coordinates if c not in all_coordinates])

    # The Maven coordinates every plugin needs, as a MODULE.bazel segment.
    #
    # These cannot be injected into maven.install() from here: MODULE.bazel is
    # not allowed to load() and an extension cannot add tags to another
    # extension. So the segment is generated, committed, and include()d, and
    # //app:plugins_check diffs the two -- the same shape as pub_path_deps_check,
    # for the same reason: the manual step is exactly the one people skip.
    #
    # It joins the *existing* @flutter_maven install rather than a repo of its
    # own. Multiple install tags with one name merge into a single resolution,
    # so a plugin and the embedding asking for different androidx versions is
    # settled once, instead of shipping both to the dexer.
    ctx.file(
        "plugin_deps.MODULE.bazel",
        _module_segment(FLUTTER_EMBEDDING_ARTIFACTS + all_coordinates),
    )

    ctx.file(
        "dart_plugin_registrant.dart",
        _DART_REGISTRANT_TEMPLATE.format(
            imports = "".join([
                "import 'package:{n}/{f}' as {n};\n".format(n = n, f = f)
                for n, _, f in dart_registrations
            ]),
            registrations = "".join([
                _DART_REGISTRATION.format(name = n, dart_class = c)
                for n, c, _ in dart_registrations
            ]),
        ),
    )

    # The one place the chosen strategy per plugin is recorded.
    ctx.file("plugins.json", json.encode({"plugins": manifest}))

    # Aggregate, so the app depends on "every native plugin" rather than on a
    # hand-maintained list that has to be edited in lockstep with pubspec.yaml.
    # `pub get` rewrites the registrant to instantiate each plugin class, so a
    # list that drifts fails the registrant compile -- loud, but still manual.
    ctx.file(
        "BUILD.bazel",
        _BUILD_HEADER +
        "exports_files([\"plugin_deps.MODULE.bazel\", \"plugins.json\", \"dart_plugin_registrant.dart\"])\n\n" +
        "android_library(\n    name = \"all\",\n    exports = [{}\n    ],\n)\n".format(
            "".join([
                "\n        \"//{n}:{n}\",".format(n = p["name"])
                for p in manifest
            ]),
        ),
    )


flutter_plugins = repository_rule(
    implementation = _flutter_plugins_impl,
    doc = "One target per native Android Flutter plugin, from .flutter-plugins-dependencies.",
    attrs = {
        "metadata": attr.label(
            doc = "The project's .flutter-plugins-dependencies, written by `pub get`.",
            allow_single_file = True,
            mandatory = True,
        ),
        "embedding": attr.string(
            doc = "Label of the flutter_embedding java_import every plugin compiles against.",
            mandatory = True,
        ),
        "defs": attr.string(
            doc = "Label of //tools/flutter:defs.bzl, for android_native_lib_jar.",
            mandatory = True,
        ),
        "abi": attr.string(
            default = "arm64-v8a",
            doc = "Android ABI native plugin code is built for.",
        ),
        "api_level": attr.int(
            default = 21,
            doc = "minSdkVersion CMake builds target; matches the app's manifest_values.",
        ),
        "overrides": attr.string_dict(
            doc = "Plugin name -> JSON list of Maven coordinates the scraper could not read.",
        ),
    },
    # ANDROID_NDK_HOME selects the NDK *and* its CMake toolchain file, so a
    # change to it has to refetch: the path is baked into the generated BUILD.
    environ = ["ANDROID_NDK_HOME"],
    local = True,
)

_project = tag_class(
    attrs = {
        "metadata": attr.label(
            doc = "The project's .flutter-plugins-dependencies.",
            allow_single_file = True,
            mandatory = True,
        ),
    },
)

# The per-plugin escape hatch. A plugin whose build.gradle cannot be read
# statically -- a BOM-supplied version, a variable from the root project -- is
# unblocked by naming its coordinates here, without touching the rules and
# without weakening the gate for anything else.
_override = tag_class(
    attrs = {
        "name": attr.string(mandatory = True, doc = "Plugin name."),
        "artifacts": attr.string_list(
            mandatory = True,
            doc = "Maven coordinates this plugin needs, group:artifact:version.",
        ),
    },
)


def _flutter_plugins_ext_impl(ctx):
    overrides = {}
    for mod in ctx.modules:
        for override in mod.tags.override:
            overrides[override.name] = json.encode(override.artifacts)
    for mod in ctx.modules:
        for project in mod.tags.project:
            flutter_plugins(
                name = "flutter_plugins",
                metadata = project.metadata,
                overrides = overrides,
                # Resolved here, in the module that owns the label, so the
                # generated repository does not have to reason about repo
                # mapping to find them.
                embedding = str(Label("//tools/flutter:flutter_embedding")),
                defs = str(Label("//tools/flutter:defs.bzl")),
            )


flutter_plugins_ext = module_extension(
    implementation = _flutter_plugins_ext_impl,
    tag_classes = {"project": _project, "override": _override},
)
