//
// Generated by //tools/flutter:plugins.bzl -- do not edit.
//
// The Dart half of plugin registration. GeneratedPluginRegistrant.java
// instantiates each plugin's *native* class; a federated plugin also ships a
// Dart implementation of its platform interface, declared as `dartPluginClass`
// in the plugin's pubspec, and that half is registered from here.
//
// Nothing imports this file. frontend_server is given it via --source, and the
// engine finds it through the `flutter.dart_plugin_registrant` environment
// define, which package:flutter/src/dart_plugin_registrant.dart reads into a
// const. Hence the vm:entry-point pragmas: nothing references these symbols, so
// tree shaking would otherwise drop them.

import 'dart:io'; // flutter_ignore: dart_io_import.

import 'package:image_picker_android/image_picker_android.dart' as image_picker_android;

@pragma('vm:entry-point')
class _PluginRegistrant {

  @pragma('vm:entry-point')
  static void register() {
    if (Platform.isAndroid) {
      try {
        image_picker_android.ImagePickerAndroid.registerWith();
      } catch (err) {
        print(
          '`image_picker_android` threw an error: $err. '
          'The app may not function as expected until you remove this plugin from pubspec.yaml'
        );
      }
    }
  }
}
