"""Tests for pub_lock_parser.bzl.

The parser is what stands between a `pubspec.lock` and a download, so what it
refuses matters as much as what it reads: an unpinned hosted package, a git
source, and a lock it does not understand must each fail loudly instead of
producing a repository that fetches something unverified.
"""

load("@bazel_skylib//lib:unittest.bzl", "analysistest", "asserts", "unittest")
load(":pub_lock_parser.bzl", "language_version", "pubspec_dependencies", "pubspec_flutter_plugin", "resolve_lock")

visibility(["//flutter"])

_SHA = "a" * 64

def _hosted(name, version = "1.0.0", sha = _SHA, url = "https://pub.dev"):
    return """  {name}:
    dependency: "direct main"
    description:
      name: {name}
      sha256: "{sha}"
      url: "{url}"
    source: hosted
    version: "{version}"
""".format(name = name, version = version, sha = sha, url = url)

_SDK_FLUTTER = """  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
"""

_PATH_GREETER = """  greeter:
    dependency: "direct main"
    description:
      path: "../greeter"
      relative: true
    source: path
    version: "0.0.1"
"""

_TAIL = """sdks:
  dart: ">=3.4.0 <4.0.0"
"""

def _lock(*entries):
    return "# Generated by pub\npackages:\n" + "".join(entries) + _TAIL

_MIXED = _lock(
    _hosted("characters", "1.4.0"),
    _hosted("http", "1.2.2", url = "https://pub.example.org/"),
    _SDK_FLUTTER,
    _PATH_GREETER,
)

def _classifies_each_source_impl(ctx):
    env = unittest.begin(ctx)
    resolved = resolve_lock(_MIXED)
    asserts.equals(env, ["characters", "http"], [p["name"] for p in resolved["hosted"]])
    asserts.equals(env, {"name": "characters", "version": "1.4.0", "sha256": _SHA, "url": "https://pub.dev"}, resolved["hosted"][0])

    # A trailing slash on the server does not leak into the download URL.
    asserts.equals(env, "https://pub.example.org", resolved["hosted"][1]["url"])
    asserts.equals(env, [{"name": "flutter", "version": "0.0.0"}], resolved["sdk"])
    asserts.equals(env, [{"name": "greeter", "version": "0.0.1", "path": "../greeter"}], resolved["path"])
    return unittest.end(env)

_classifies_each_source_test = unittest.make(_classifies_each_source_impl)

def _empty_lock_impl(ctx):
    env = unittest.begin(ctx)
    asserts.equals(env, {"hosted": [], "sdk": [], "path": []}, resolve_lock("packages: {}\nsdks:\n  dart: \">=3.0.0 <4.0.0\"\n"))
    return unittest.end(env)

_empty_lock_test = unittest.make(_empty_lock_impl)

def _pubspec_readers_impl(ctx):
    env = unittest.begin(ctx)
    asserts.equals(env, "3.4", language_version("name: x\nenvironment:\n  sdk: ^3.4.0\n  flutter: \">=3.0.0\"\n"))
    asserts.equals(env, "2.7", language_version("name: x\n"))
    asserts.equals(env, ["a", "b"], pubspec_dependencies("dependencies:\n  b: ^1.0.0\n  a:\n    sdk: flutter\ndev_dependencies:\n  c: any\n"))
    asserts.equals(
        env,
        ("", {"package": "com.example.p", "pluginClass": "P"}),
        pubspec_flutter_plugin("flutter:\n  plugin:\n    platforms:\n      android:\n        package: com.example.p\n        pluginClass: P\n      ios:\n        pluginClass: Q\n"),
    )
    asserts.equals(env, ("", None), pubspec_flutter_plugin("flutter:\n  plugin:\n    platforms:\n      ios:\n        pluginClass: Q\n"))

    # `implements` sits beside `platforms`; one under a platform block is not it.
    asserts.equals(
        env,
        ("fed", {"package": "com.example.alt", "pluginClass": "Alt"}),
        pubspec_flutter_plugin("flutter:\n  plugin:\n    implements: fed\n    platforms:\n      android:\n        package: com.example.alt\n        pluginClass: Alt\n"),
    )
    asserts.equals(
        env,
        ("", {"default_package": "fed_android"}),
        pubspec_flutter_plugin("flutter:\n  plugin:\n    platforms:\n      android:\n        default_package: fed_android\n      web:\n        implements: other\n"),
    )
    return unittest.end(env)

_pubspec_readers_test = unittest.make(_pubspec_readers_impl)

def _resolve_only_impl(ctx):
    resolve_lock(ctx.attr.lock)
    return []

_resolve_only = rule(
    implementation = _resolve_only_impl,
    attrs = {"lock": attr.string(mandatory = True)},
)

def _rejects_impl(ctx):
    env = analysistest.begin(ctx)
    asserts.expect_failure(env, ctx.attr.message)
    return analysistest.end(env)

_rejects_test = analysistest.make(
    _rejects_impl,
    expect_failure = True,
    attrs = {"message": attr.string(mandatory = True)},
)

def _rejects(name, lock, message):
    _resolve_only(name = name + "_subject", lock = lock, tags = ["manual"])
    _rejects_test(name = name, target_under_test = ":" + name + "_subject", message = message)
    return name

def pub_lock_parser_test_suite(name):
    """Instantiates every parser test and a suite named `name` holding them.

    Args:
      name: name of the suite and prefix of every test target.
    """
    unittest.suite(
        name + "_reads",
        _classifies_each_source_test,
        _empty_lock_test,
        _pubspec_readers_test,
    )
    tests = [name + "_reads"]
    for case, lock, message in [
        (
            "git_source",
            _lock("""  dep:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: 0123456789abcdef0123456789abcdef01234567
      url: "https://github.com/example/dep.git"
    source: git
    version: "1.0.0"
"""),
            "git sources are not supported",
        ),
        ("missing_sha256", _lock(_hosted("http").replace('      sha256: "{}"\n'.format(_SHA), "")), "refusing to fetch an unpinned archive"),
        ("short_sha256", _lock(_hosted("http", sha = "abc")), "no usable sha256"),
        ("uppercase_sha256", _lock(_hosted("http", sha = "A" * 64)), "no usable sha256"),
        ("plain_http_server", _lock(_hosted("http", url = "http://pub.example.org")), "non-https server"),
        ("hosted_description_names_another_package", _lock(_hosted("http").replace("name: http", "name: other")), "names \"other\" in its description"),
        ("unusable_version", _lock(_hosted("http", version = "1.0/../x")), "unusable version"),
        ("unknown_source", _lock(_SDK_FLUTTER.replace("source: sdk", "source: mirror")), "unknown source"),
        ("non_flutter_sdk", _lock(_SDK_FLUTTER.replace("description: flutter", "description: fuchsia")), "only flutter is modelled"),
        ("absolute_path_package", _lock(_PATH_GREETER.replace("relative: true", "relative: false")), "must be a relative path dependency"),
        ("package_name_with_path_characters", _lock(_hosted("../evil")), "is not a valid package name"),
        ("duplicate_package", _lock(_hosted("http"), _hosted("http")), "duplicate package"),
        ("tab_indentation", "packages:\n\tx:\n", "tab indentation"),
        ("unknown_top_level_key", "packages: {}\nextras: {}\n", "unknown top-level key"),
        ("unsupported_yaml_construct", _lock(_hosted("http").replace('"1.0.0"', "&anchor")), "unsupported YAML construct"),
    ]:
        tests.append(_rejects(name + "_rejects_" + case, lock, message))
    native.test_suite(name = name, tests = tests)
