"""GeneratedPluginRegistrant.java, as flutter_tools writes it.

Pure Starlark: the pub hub calls it with the pubspecs it already holds, and
//tests/registrant_parity compares its output with what
`flutter build apk --config-only --{debug,release}` write (debug is also what
`flutter pub get` writes). Parity target:
flutter_tools 3.47.3, `lib/src/flutter_plugins.dart`.

Debug keeps dev-only plugins; release drops them *before* federated resolution,
as `injectPlugins(releaseMode: true)` does, so a dev-only implementation can
change which candidate wins.
"""

visibility(["//flutter", "//tests/..."])

# `_androidPluginRegistryTemplateNewEmbedding`, rendered. Mustache drops the
# standalone section-tag lines, so each entry is exactly these five lines.
_HEADER = """package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
"""

_ENTRY = """    try {{
      flutterEngine.getPlugins().add(new {cls}());
    }} catch (Exception e) {{
      Log.e(TAG, "Error registering plugin {name}, {cls}", e);
    }}
"""

_FOOTER = """  }
}
"""

# `AndroidPlugin._getSupportedEmbeddings`: a main class mentioning this is V2.
_V2_MARKER = "io.flutter.embedding.engine.plugins.FlutterPlugin"

def android_plugin(name, implements, android, direct, dev):
    """One package's Android plugin facts, in the shape the resolver reads.

    Args:
      name: the package name.
      implements: `flutter.plugin.implements`, or "".
      android: the `flutter.plugin.platforms.android` block, or None.
      direct: whether the app lists it under `dependencies` (not dev).
      dev: whether only the app's dev_dependencies reach it.

    Returns:
      A dict, or None when the package has no Android block.
    """
    if android == None:
        return None
    default_package = android.get("default_package")
    return {
        "name": name,
        "implements": implements,
        "default_package": default_package,
        # `Plugin._providesImplementationForPlatform`: a `default_package` block
        # only points elsewhere.
        "inline": default_package == None,
        "package": android.get("package"),
        "plugin_class": android.get("pluginClass"),
        "direct": direct,
        "dev": dev,
    }

def resolve_android_plugins(plugins, release):
    """The Android implementations flutter_tools registers, sorted by name.

    `_resolvePluginImplementationsByPlatform` for `nativeOrDart`, after
    `injectPlugins`' release filter. Fails where flutter_tools exits.

    Args:
      plugins: android_plugin() results.
      release: drop dev-only plugins first.

    Returns:
      The chosen plugin dicts.
    """
    if release:
        plugins = [p for p in plugins if not p["dev"]]
    by_name = {p["name"]: p for p in plugins}

    candidates = {}
    defaults = {}
    for p in plugins:
        name = p["name"]
        default_name = p["default_package"]
        if default_name != None:
            # `_validatePlugin`. The inline-plus-default conflict cannot arise
            # here: a block with `default_package` is never inline.
            if p["implements"] and not (p["implements"] == name and default_name == name):
                fail(("Plugin {}:android provides an implementation for {} and also references " +
                      "a default implementation for {}, which flutter_tools rejects.").format(
                    name,
                    p["implements"],
                    default_name,
                ))
        elif p["inline"]:
            default_name = name

        # A missing or non-inline default only warns in flutter_tools.
        if default_name != None and default_name in by_name and by_name[default_name]["inline"]:
            defaults[name] = by_name[default_name]

        if p["inline"]:
            implemented = p["implements"] or name
            candidates.setdefault(implemented, []).append(p)

    chosen = []
    for implemented in candidates:
        found = candidates[implemented]
        if len(found) == 1:
            chosen.append(found[0])
            continue
        direct = [p for p in found if p["direct"]]
        if len(direct) == 1:
            chosen.append(direct[0])
            continue
        if direct:
            implementing = [p for p in direct if p["implements"]]
            if len(implementing) == 1 and len(direct) == 2:
                chosen.append(implementing[0])
                continue
            fail(("Plugin {}:android has conflicting direct dependency implementations: {}. " +
                  "Remove all but one of them from pubspec.yaml.").format(
                implemented,
                ", ".join([p["name"] for p in direct]),
            ))
        default = defaults.get(implemented)
        if default != None and default in found:
            chosen.append(default)
            continue
        fail(("Plugin {}:android has multiple possible implementations: {}. " +
              "Add one of them to pubspec.yaml.").format(
            implemented,
            ", ".join([p["name"] for p in found]),
        ))
    return sorted(chosen, key = lambda p: p["name"])

def supports_embedding_v2(main_class_text):
    """Whether flutter_tools would register this main class.

    Args:
      main_class_text: the plugin's main class source.

    Returns:
      True when the class implements the V2 FlutterPlugin.
    """
    return _V2_MARKER in main_class_text

def main_class_candidates(package, plugin_class):
    """Package-root-relative paths flutter_tools looks for the main class at.

    Args:
      package: the android block's `package`.
      plugin_class: the android block's `pluginClass`.

    Returns:
      The Java path, then the Kotlin one.
    """
    base = "android/src/main/{}/" + package.replace(".", "/") + "/" + plugin_class
    return [base.format("java") + ".java", base.format("kotlin") + ".kt"]

def render_android_registrant(entries):
    """GeneratedPluginRegistrant.java for the given registrations.

    Args:
      entries: (plugin name, fully qualified main class) pairs, in order.

    Returns:
      The file content, byte for byte what flutter_tools writes.
    """
    return _HEADER + "".join([_ENTRY.format(name = n, cls = c) for n, c in entries]) + _FOOTER
