package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.example.parity.alpha.AlphaKotlinPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin alpha_kotlin, com.example.parity.alpha.AlphaKotlinPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.parity.gamma.SharedGammaPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin shared_gamma, com.example.parity.gamma.SharedGammaPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.parity.eta.TransitiveEtaPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin transitive_eta, com.example.parity.eta.TransitiveEtaPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.parity.zeta.ZetaJavaPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin zeta_java, com.example.parity.zeta.ZetaJavaPlugin", e);
    }
  }
}
