"""Synthesizes portable metadata for the fake plugin fixture.

Pub writes absolute package paths into both metadata files, so checked-in copies
are machine-specific. Resolve the marker at fetch time and generate only those
files; the plugin sources remain checked in.
"""

def _fake_plugin_metadata_impl(ctx):
    # The marker is the plugin's pubspec, so its parent is the package root.
    root = str(ctx.path(ctx.attr.marker).dirname)
    ctx.file(
        ".flutter-plugins-dependencies",
        json.encode({
            "info": "Generated by //fixtures:plugin_fixture.bzl -- do not edit or check into version control.",
            "plugins": {
                "android": [
                    {
                        "name": "fake_plugin",
                        "path": root + "/",
                        "native_build": True,
                        "dependencies": [],
                        "dev_dependency": False,
                    },
                ],
            },
        }),
    )
    ctx.file(
        "package_config.json",
        json.encode({
            "configVersion": 2,
            "packages": [
                {
                    "name": "fake_plugin",
                    "rootUri": "file://" + root,
                    "packageUri": "lib/",
                    "languageVersion": "3.0",
                },
            ],
        }),
    )
    ctx.file(
        "BUILD.bazel",
        "exports_files([\".flutter-plugins-dependencies\", \"package_config.json\"])\n",
    )

fake_plugin_metadata = repository_rule(
    implementation = _fake_plugin_metadata_impl,
    attrs = {
        "marker": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "A file at the fake plugin's package root, read only for its absolute location.",
        ),
    },
)
