"""Recipes that patch around generator gaps, for smooth_app's plugin set.

Consumer code. Every macro here exists because the *standard* build mishandles
the plugin, not because the plugin falls outside the standard model -- the
second use of recipes described in docs_internal/package-recipes.md. Each is a
few lines on top of what the generator already worked out, and each should be
deleted when the corresponding generator gap is closed.

That is the point of the mechanism: a project is not blocked waiting for a fix
in the rules. The `# GAP:` note on each says what would retire it.
"""

# `@@` is load bearing -- see _RECIPE_TEMPLATE in //tools/flutter:plugins.bzl.
# buildifier: disable=canonical-repository
load("@@//tools/flutter:recipe.bzl", "flutter_native_contribution")
load("@rules_android//rules:rules.bzl", "android_library")
load("@rules_kotlin//kotlin:android.bzl", "kt_android_library")

def _no_native(name):
    """Declare that this package contributes no native library, deliberately.

    Every recipe must define `<name>_flutter_native`; the generated aggregate
    depends on that name, so a recipe that forgets one fails at analysis rather
    than producing a target nothing references. These recipes patch a *build*
    and ship no .so, so they say so explicitly -- which is what `empty` is for.
    Staying silent is the failure this convention exists to catch.
    """
    flutter_native_contribution(name = name + "_flutter_native", empty = True)

def _srcs(info, extension):
    """Sources by extension, recovered from the staged tree rather than trusted.

    `info.android_srcs` is the generator's classification, and classification is
    what these recipes are routing around, so they read `all_files` instead.
    """
    return [
        f
        for f in info.all_files
        if f.startswith("android/src/main/") and f.endswith(extension)
    ]

# --- url_launcher_android ----------------------------------------------------

_BUILD_CONFIG = """// Generated by //bazel/flutter:smooth_app_fixes.bzl.
package {package};

public final class BuildConfig {{
    public static final boolean DEBUG = false;
}}
"""

def url_launcher_android_recipe(name, info):
    """url_launcher_android reads its own BuildConfig.DEBUG.

    # GAP: AGP generates a BuildConfig class for every module, carrying DEBUG,
    # APPLICATION_ID, BUILD_TYPE and VERSION_NAME. Nothing here generates one, so
    # `UrlLauncher.java:71: cannot find symbol: variable BuildConfig`. Retire this
    # when the generator emits a BuildConfig per plugin.
    """
    native.genrule(
        name = name + "_build_config",
        outs = ["BuildConfig.java"],
        cmd = "cat > $@ <<'EOF'\n" + _BUILD_CONFIG.format(package = info.namespace) + "EOF",
    )
    _no_native(name)

    kt_android_library(
        name = name,
        srcs = _srcs(info, ".java") + _srcs(info, ".kt") + [":" + name + "_build_config"],
        manifest = info.android_manifest,
        custom_package = info.namespace,
        exports_manifest = 1,
        resource_files = info.resource_files,
        deps = [info.embedding] + info.plugin_deps + info.coordinates,
    )

# --- mobile_scanner ----------------------------------------------------------

def mobile_scanner_recipe(name, info):
    """mobile_scanner calls ListenableFuture, which arrives only transitively.

    # GAP: CameraX's `ProcessCameraProvider.getInstance()` returns a guava
    # ListenableFuture, and the plugin uses it directly -- but its build.gradle
    # never names guava, so the scraper cannot attribute it and Bazel's strict
    # deps refuse the indirect use. Retire this when the generator can add the
    # transitives a plugin actually compiles against.
    """
    kt_android_library(
        name = name,
        srcs = _srcs(info, ".java") + _srcs(info, ".kt"),
        manifest = info.android_manifest,
        custom_package = info.namespace,
        exports_manifest = 1,
        resource_files = info.resource_files,
        deps = [info.embedding] + info.plugin_deps + info.coordinates + [
            "@flutter_maven//:com_google_guava_guava",
        ],
    )
    _no_native(name)

# --- sqflite_android ---------------------------------------------------------

def sqflite_android_recipe(name, info):
    """sqflite_android imports org.jetbrains.annotations.NotNull.

    # GAP: that annotation rides in with kotlin-stdlib, which the scraper skips
    # deliberately (the rules_kotlin toolchain supplies it). This plugin is Java
    # and imports the type directly, so strict deps wants it declared. Retire
    # this when skipping kotlin-stdlib stops also dropping its annotations jar.
    """
    android_library(
        name = name,
        srcs = _srcs(info, ".java") + _srcs(info, ".kt"),
        manifest = info.android_manifest,
        custom_package = info.namespace,
        exports_manifest = True,
        resource_files = info.resource_files,
        deps = [info.embedding] + info.plugin_deps + info.coordinates + [
            "@flutter_maven//:org_jetbrains_annotations",
        ],
    )
    _no_native(name)

# --- shared_preferences_android ----------------------------------------------

def shared_preferences_android_recipe(name, info):
    """shared_preferences_android needs DataStore's *Android* variant.

    # GAP: not ours. `preferencesDataStore` is an Android-only extension on
    # Context and lives in `datastore-preferences-android`, but the Gradle
    # resolver resolves KMP modules as a plain JVM consumer, so only
    # `datastore-preferences-jvm` enters the graph --
    # rules_jvm_external#1605, which names androidx.datastore explicitly.
    #
    # The fix is the `artifacts` half of plugins.package() -- it forces the
    # android variant into the single maven.install at module time, which a
    # macro could never do on its own. Nothing extra is needed here: coordinates
    # supplied that way arrive in `info.coordinates` already, so the two halves
    # of the tag join up without the recipe restating anything. Adding it by
    # hand as well is an error ("Label is duplicated in the deps attribute").
    #
    # So this macro is the *standard* body, and exists only to prove the
    # analysis half is reachable. Once #1605 lands it can go entirely, leaving
    # just the artifacts line -- and then that goes too.
    """
    kt_android_library(
        name = name,
        srcs = _srcs(info, ".java") + _srcs(info, ".kt"),
        manifest = info.android_manifest,
        custom_package = info.namespace,
        exports_manifest = 1,
        resource_files = info.resource_files,
        deps = [info.embedding] + info.plugin_deps + info.coordinates,
    )
    _no_native(name)
